[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "tasq-client-python"
version = "0.1.19"
dependencies = ["requests"]

[tool.setuptools]
packages = ["tasq_client"]
